### ISSUE TITLE
Servers for Oxhack

### ISSUE THREAD

**Issue by JaredReabow** [londonhackspace/hackneyroad#12]
As per my chat on your IRC, if London Hackspace happens across or is getting rid of rack mount servers, could you think of us :)
you can contact the staff of oxhack via staff@oxhack.org
thanks

**Comment by friedkiwi** [comment]
I've been lobbying for a while already, it's a WIP. Essentially I need to get unbusied from work to coordinate something.

Biggest challenge would be transport though - I'm not really planning to drag them to Bethnal Green, then to Lancaster Gate, then to Paddington and then to Science Oxford. I still need my back.

@JasperWallace should know more about what we've got left.

**Comment by padski** [comment]
I may well be able to sort that for fuel cost...any idea of date?

**Comment by JaredReabow** [comment]
Not sure yet but next wednesday or friday i will be driving to Leicester , as such i should be able to pick them up if they are suitable to our needs as we have a few specific requirements.
thanks guys for the help :)

**Comment by JasperWallace** [comment]
All done now, they also got an older ethernet switch, a poe midspan, and an avocent thingy.
