### ISSUE TITLE
gill has died

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/hackneyroad#15]
the sd card is corrupt. It will need re-installing.

Gill does the bus times and has an airpi for environment monitoring.

**Comment by ivankocienski** [comment]
I think Dean Swift is 'fixing' it

**Comment by JasperWallace** [comment]
yup, he pointed it out to me, i need to come over and grab it and rebuild it.

**Comment by JasperWallace** [comment]
gill is now at home with me being rebuilt.

**Comment by JasperWallace** [comment]
rebuilt and back at the space.
Not had a chance to restore the old accounts and airpi stuff yet (massive yak shaving going on atm :crying_cat_face: :person_frowning:  )

**Comment by JasperWallace** [comment]
gah, now on jessie, so systemd, so inittab does not work, so ???

**Comment by JasperWallace** [comment]
working with the bus times now, needs the airpi stuff fixing

**Comment by JasperWallace** [comment]
airpi stuff sort of working, cacti has badly bitrotted
